name: on_off
description: ON & OFF Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  build_runner: ^2.2.0
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  json_annotation: ^4.6.0
  path: ^1.8.1
  path_provider: ^2.0.11
  provider: ^6.0.3
  sqflite: ^2.0.3
  table_calendar: ^3.0.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  mockito: ^5.2.0
  sqflite_common_ffi: ^2.1.1+1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - lib/ui/off/list/
